# Generated by Django 3.0.5 on 2021-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='ID отзыва'),
        ),
    ]
